# Array Math in Numpy

Numpy enables both elementwise and matrix operations. Many operations are implemented as both functions and methods of numpy object instances. 

In [1]:
import numpy as np

In [2]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print('x:\n', x)
print('y:\n', y)

x:
 [[1 2]
 [3 4]]
y:
 [[5 6]
 [7 8]]


## Elementwise addition, subtraction, division and multiplication

`np.add()` is equivalent to the `+` operator and performs elementwise addition

In [3]:
z1 = x + y
z2 = np.add(x, y)
print('z1:\n', z1)
print('z2:\n', z2)

z1:
 [[ 6  8]
 [10 12]]
z2:
 [[ 6  8]
 [10 12]]


Likewise, `np.subtract()` is equivalent to the `-` operator and performs elementwise subtraction

In [4]:
z3 = y - x
z4 = np.subtract(y, x)
print('z3:\n', z3)
print('z4:\n', z4)

z3:
 [[4 4]
 [4 4]]
z4:
 [[4 4]
 [4 4]]


`np.multiply()` is equivalent to `*`; `np.divide` is equivalent to `/`

In [5]:
z5 = x * y
z6 = np.multiply(x, y)
z7 = y/x
z8 = np.divide(y, x)
print('z5:\n', z5)
print('z6:\n', z6)
print('z7:\n', z7)
print('z8:\n', z8)

z5:
 [[ 5 12]
 [21 32]]
z6:
 [[ 5 12]
 [21 32]]
z7:
 [[ 5.          3.        ]
 [ 2.33333333  2.        ]]
z8:
 [[ 5.          3.        ]
 [ 2.33333333  2.        ]]


`np.sqrt()` performs elementwise square root - **not the same as `math.sqrt()`**

In [6]:
z9 = np.sqrt(y)
print('z9:\n', z9)

z9:
 [[ 2.23606798  2.44948974]
 [ 2.64575131  2.82842712]]


## Matrix Multiplication

We saw above that `*` performs elementwise multiplication. To do matrix multiplication (inner product), use `np.dot()`, available as both a function and a method of numpy array objects. 

In [7]:
a = np.array([9, 10])
b = np.array([4, 5])
print('a:\n', a)
print('b:\n', b)
print('x:\n', x)
print('y:\n', y)

a:
 [ 9 10]
b:
 [4 5]
x:
 [[1 2]
 [3 4]]
y:
 [[5 6]
 [7 8]]


### Vector-vector dot product

Produces a scalar

In [8]:
c1 = np.dot(a, b)
c2 = a.dot(b)
print('c1:\n', c1)
print('c2:\n', c2)

c1:
 86
c2:
 86


### Matrix-vector dot product

Produces a vector (rank 1 array)

In [9]:
d1 = np.dot(x, a)
d2 = x.dot(a)
print('d1:\n', d1)
print('d2:\n', d2)

d1:
 [29 67]
d2:
 [29 67]


### Matrix-matrix dot product

Produces a matrix (rank 2 array)

In [10]:
e1 = np.dot(x, y)
e2 = x.dot(y)
print('e1:\n', e1)
print('e2:\n', e2)

e1:
 [[19 22]
 [43 50]]
e2:
 [[19 22]
 [43 50]]


## Sum over rows, columns, or entire arrays

In [11]:
x

array([[1, 2],
       [3, 4]])

### Sum entire array

In [12]:
np.sum(x)

10

### Sum over rows

In [13]:
np.sum(x, axis=1)

array([3, 7])

### Sum over columns

In [14]:
np.sum(x, axis=0)

array([4, 6])