# Indexing Numpy Arrays

Numpy is zero-indexed! 

Here we will look at:

* Slicing
* Integer indexing
* Boolean indexing

In [35]:
import numpy as np

## Slicing

* Slicing numpy arrays works like base-Python list slicing. 
* A slice must be specified for each dimension of the array. 


In [36]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
b = a[:3, 1:4]
b

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

Modifying a slice modifies the original array:

In [38]:
b[0, 0] = 5000
a

array([[   1, 5000,    3,    4],
       [   5,    6,    7,    8],
       [   9,   10,   11,   12]])

Select a full row:

In [39]:
a[2, :]

array([ 9, 10, 11, 12])

Select a full column:

In [40]:
a[:, 2]

array([ 3,  7, 11])

## Integer indexing

Integer indexing works by specifying the elements using their row/column/higher-dimensional indexes:

In [41]:
b = np.array([[1,2], [3,4], [5,6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
b[0, 0]

1

### Selecting multiple elements

We can specify a list of row indices and a list of column indices:

In [43]:
b[[0,1,2], [0,1,0]] 

array([1, 4, 5])

Equivalently:

In [44]:
np.array([b[0, 0], b[1, 1], b[2, 0]])

array([1, 4, 5])

### Mutating an element in each row/column

In [45]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
# create array of indexes
idx = np.array([3, 0, 1])

# select from a using idx
print(a[np.arange(3), idx])

# mutate an element in each row using idx
a[np.arange(3), idx] += 100
a


[ 4  5 10]


array([[  1,   2,   3, 104],
       [105,   6,   7,   8],
       [  9, 110,  11,  12]])

## Integer indexing and slicing

When integer indexing is mixed with slicing, the result is an array of **lower rank** than the original:

In [47]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
row0_rank1 = a[1, :]
print(row0_rank1)
row0_rank1.shape

[5 6 7 8]


(4,)

In [49]:
row0_rank2 = a[1:2, :]
print(row0_rank2)
row0_rank2.shape

[[5 6 7 8]]


(1, 4)

## Boolean indexing

Use to select on the basis of a condition

In [50]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Construct boolean array based on a condition

In [51]:
b = a >= 6
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

Select on the basis of that boolean array

In [52]:
a[b]

array([ 6,  7,  8,  9, 10, 11, 12])

This is equivalent to the following single line:

In [53]:
a[a >= 6]

array([ 6,  7,  8,  9, 10, 11, 12])