# Initializing Numpy Arrays 

A numpy array has values of all the same type, indexed by non-negative integers.

* **Rank:** Number of dimensions of array
* **Shape:** Length of each dimensions

Numpy arrays can be initialized using nested lists, with elements accessed using square brackets. Numpy has simply methods for creating identity matrices, and arrays of zeros, constants, and ones.

In [1]:
import numpy as np

## Initialize rank-1 array

In [3]:
a = np.array([1, 2, 3])
print(type(a))
print(a.shape)
a[0]

<class 'numpy.ndarray'>
(3,)


1

## Initialize rank-2 array

In [5]:
b = np.array([[1,2,3], [4,5,6]])
print(b.shape)
b[1, 0]

(2, 3)


4

## Array of zeros

Note double brackets!

In [8]:
z = np.zeros((3, 3))
z

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

## Array of ones


In [11]:
i = np.ones((4, 2))
i

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

## Array of constant 

In [12]:
c = np.full((3, 4), 6)
c

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

## Identity matrix

In [13]:
eye = np.eye(3)
eye

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

## Array of random numbers

Note double brackets!

In [14]:
r = np.random.random((3,3))
r

array([[ 0.83581607,  0.52275483,  0.31765733],
       [ 0.53204141,  0.84209013,  0.58223626],
       [ 0.83766886,  0.10384035,  0.98604269]])